# Generated by Django 4.0.5 on 2022-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlantillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.CharField(max_length=1200),
        ),
    ]
