# Generated by Django 4.0.5 on 2022-08-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlantillas', '0002_alter_mensaje_emisor_alter_mensaje_receptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='cuerpo',
            new_name='asunto',
        ),
    ]
