# Generated by Django 4.0.5 on 2022-08-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlantillas', '0003_rename_cuerpo_mensaje_asunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='asunto',
            new_name='cuerpo',
        ),
    ]
