# Generated by Django 4.0.5 on 2022-08-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlantillas', '0004_rename_asunto_mensaje_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1200)),
                ('subtitulo', models.CharField(max_length=1200)),
                ('imagen', models.ImageField(upload_to='')),
                ('cuerpo', models.CharField(max_length=1200)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
