# Generated by Django 4.0.5 on 2022-08-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlantillas', '0008_blog_image_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='image',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
